### PR TITLE
OAuth2 Auth provider incorrectly validating Access Tokens

### PR DESCRIPTION
**Pull request by byn-florian-posch**
Motivation:

PR containing code for fix in #654

### CODE REVIEW

**Comment by vietj** [comment]
I can't see any test for this

**Comment by vietj** [comment]
@pmlopes could you have a look ?

**Comment by byn-florian-posch** [comment]
> I can't see any test for this

I didn't write a test because I couldn't see any for the provider. A full maven build for the whole vertx-auth module passes locally but that's as far as I ran tests locally.

**Comment by byn-florian-posch** [comment]
Test issues partially fixed, reusing the _audience_ ArrayList from JWTOptions did unintendedly modify its content, using a copy now.

**Comment by byn-florian-posch** [comment]
Now only the following two tests are failing in _OAuth2Keycloak14IT_ 

- discoverGetTokenFromFrontEndPerformAuthWithBackend
- discoverGetTokenFromFrontEndPerformAuthWithBorkendWillFail

Tests are expecting validation to fail but that isn't happening with the suggested ID-token-only validation. I don't want to tamper with existing tests too much, so your opinion on this one would be appreciated.

**Comment by byn-florian-posch** [comment]
@pmlopes @vietj May I ask for an update?

My recent changes to suggested fix from https://github.com/eclipse-vertx/vertx-auth/issues/654 did resolve some of the regression but the ones are broken with new logic only validating ID-tokens. Writing a meaningful test is above my paygrade and I wouldn't dare to just remove the test cases. 

Let me know what you think,

**Comment by byn-florian-posch** [comment]
There hasn't been any reply, neither on the related [issue](https://github.com/eclipse-vertx/vertx-auth/issues/654) nor here for months and I'm not sure how else to address this.

**Comment by byn-florian-posch** [comment]
We decided to tackle this issue by this issue by managing audiences in our application in a controlled manner, so no need to fix token handling from our perspective -> closing the PR and leave it to the creator of the related [issue ](https://github.com/eclipse-vertx/vertx-auth/issues/654)how to deal with it. 

See also https://github.com/eclipse-vertx/vertx-auth/issues/654

**Pull request closed without merging**
