### PR TITLE
Initial work, Authorizations are now CoW Immutable which should solve…

### PR DESCRIPTION
**Pull request by pmlopes**
… issues with multiple access across event loops

### CODE REVIEW

**Comment by pmlopes** [comment]
@bfreuden this should address the issue #541 

The idea is that in vert.x 5 as we can break APIs we make the Authorizations a Immutable data structure and apply CoW semantics so multiple threads can access and see the data they saw when started, and not be afected by future mutations.

**Comment by pmlopes** [comment]
The PR is still draft as I'd like to get rid of the `add` method which causes too much copies (ATM it only affects 20 places in tests) and your reproducer is always green for me.

**Comment by pmlopes** [comment]
The reproducer now works 100% good and it takes 1.3s to execute vs 2.6s with lock

**Comment by bfreuden** [comment]
@pmlopes 
Wow! Thank you so much! :+1: 
Can't wait to try it out!

**Pull request merged**
