### PR TITLE
Mongo auth service

### PR DESCRIPTION
**Pull request by remi128**
first version of an authentication service for mongo db. In the first version passwords are stored as clear text, preparation for encryption is done but not yet implemented.

### CODE REVIEW

**Comment by purplefox** [comment]
thanks, will take a look soon :)

**Comment by purplefox** [comment]
Hi Michael-

This doesn't build for me - your changes seem out of sync with the AuthProvider/AuthService API:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project vertx-auth-service: Compilation failure: Compilation failure:
[ERROR] /home/tim/projects/vert-x3/vertx-auth-service/src/main/java/io/vertx/ext/auth/mongo/MongoAuthProvider.java:[9,29] package io.vertx.ext.auth.spi does not exist
[ERROR] /home/tim/projects/vert-x3/vertx-auth-service/src/main/java/io/vertx/ext/auth/mongo/MongoAuthProvider.java:[20,43] cannot find symbol
[ERROR] symbol: class AuthProvider

**Comment by remi128** [comment]
yes, you're right. i merged my branch into master and saw problems. 
Tell me: when i uploaded the changes into my fork, do i have to create a new PR oder can i update the current one?

**Comment by purplefox** [comment]
You don't need a new PR. When you push changes to your fork they will automatically appear in the old PR.

**Comment by remi128** [comment]
hey Tim,

can you check? Normally it should work now.

**Comment by remi128** [comment]
hey tim,

just a question: is the mongo auth of interest? Cause i plan to add password crypt now. If not, then i will bring it into an external project, so that its not disturbing.

**Comment by purplefox** [comment]
Yes, it's of interest, but we're just incredibly busy trying to get everything don before 3.0 final :)

**Comment by purplefox** [comment]
Hi Remi - I am still interested in this but we can't merge as is after the latest refactor/rename.

Also you might want to look at password hashing/salt that I implemented in the jdbc auth implementation see: https://github.com/vert-x3/vertx-auth/pull/14

You may be able to reuse much of this implementation, the main difference being in that one it uses a JDBCClient but in yours you would use a MongoClient.

**Comment by remi128** [comment]
sorry, was busy. i saw, that the last changes are quite complete :-)
I'll probably reimplement my work on a new fork and will create a new PR when finished. Thus i will close this PR, ok?

**Pull request closed without merging**
