### PR TITLE
Started cleaning the code and comply to the specs

### PR DESCRIPTION
**Pull request by pmlopes**
Solves: https://github.com/vert-x3/vertx-auth/issues/319

### CODE REVIEW

**Comment by sberyozkin** [comment]
@pmlopes Hi Paulo, thanks for this fix, I've noticed `client_id` and `client_secret` are now not being sent (as I believe they are already being posted as part of the Authorization header) which looks good.
Thanks

**Comment by pmlopes** [comment]
Yes they are in the http header as per spec.

**Comment by sberyozkin** [comment]
LGTM, thanks

**Comment by sberyozkin** [comment]
@pmlopes Hi Paulo, FYI, I can't approve by pressing some button as I don't see it, only `LGTM`, so please merge unless you are expecting more reviews, thanks

**Comment by pmlopes** [comment]
This fix has been merged with https://github.com/vert-x3/vertx-auth/pull/343

**Pull request closed without merging**
