### PR TITLE
fix: fixed issues in TPM attestation for ECC

### PR DESCRIPTION
**Pull request by podlesrafal**
Motivation:

fixed issues in TPM attestation for ECC: buffer position, reading x and y, parsing crv, compare curveId

Conformance:

You should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

### CODE REVIEW

**Comment by podlesrafal** [comment]
@pmlopes please review.

**Comment by podlesrafal** [comment]
@vietj could you review?

**Comment by podlesrafal** [comment]
@vietj please review

**Comment by vietj** [comment]
thanks @podlesrafal can you backport to 4.x branch ?

**Pull request merged**
