### PR TITLE
Followup feature/otp/hotp

### PR DESCRIPTION
**Pull request by pmlopes**
Motivation:

Continue the work on #488

This is a reviewed branch that continues the work on the previous PR.

The goal is to align the API with the rest of the modules.

### CODE REVIEW

**Comment by pmlopes** [comment]
@otricadziziusz I'm proposing a few changes here. The goal is to make OtpKey a POJO so it can be used easily. The POJO emcapsulates the use of Base32 so we don't leak the dependency on apache commons (plus make it more polyglot friendly).

I've also merged the URI generation method into the HotpAuth interface as they seem natural to me to go together as building the URLs does require both config, the key and the hotp options.

**Comment by pmlopes** [comment]
@otricadziziusz I've made the provider stateless, like in webauthn. This also means that the example test app is smaller now:

```java
package org.acme;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Vertx;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.auth.otp.Authenticator;
import io.vertx.ext.auth.otp.OtpKey;
import io.vertx.ext.auth.otp.OtpKeyGenerator;
import io.vertx.ext.auth.otp.hotp.HotpAuth;
import io.vertx.ext.auth.otp.hotp.HotpCredentials;
import io.vertx.ext.web.Router;
import io.vertx.ext.web.handler.BodyHandler;

import net.glxn.qrgen.core.image.ImageType;
import net.glxn.qrgen.javase.QRCode;

public class Foo extends AbstractVerticle {

  private final AuthenticatorDataBase DB = new AuthenticatorDataBase();

  public static void main(String[] args) {
    Vertx.vertx().deployVerticle(new Foo());
  }

  private static final String ID = "Paulo";

  @Override
  public void start() {

    OtpKeyGenerator keyGen = OtpKeyGenerator.create();
    HotpAuth hotp = HotpAuth.create()
      .authenticatorFetcher(DB::fetch)
      .authenticatorUpdater(DB::upsert);

    Router app = Router.router(vertx);
    // for form data parsing
    app.route().handler(BodyHandler.create());

    app.get("/register")
      .handler(ctx -> {
        OtpKey otpKey = keyGen.generate();

        System.out.println(otpKey.getKey());
        // Create user in the database
        final Authenticator authenticator = new Authenticator(true)
          .setIdentifier(ID)
          .setKey(otpKey.getKey())
          .setAlgorithm(otpKey.getAlgorithm())
          .setCounter(0);

        DB.upsert(authenticator)
        .onFailure(ctx::fail)
        .onSuccess(v -> ctx.response()
          .putHeader("Content-Type", "image/png")
          .end(
            Buffer.buffer(
              QRCode
                .from(hotp.generateUri(otpKey, authenticator.getCounter(), "service_1", ID))
                .to(ImageType.PNG)
                .withSize(512, 512)
                .stream()
                .toByteArray())));
      });

    app.post("/verify")
      .handler(ctx -> {
        String code = ctx.getBodyAsJson().getString("code");

        hotp.authenticate(new HotpCredentials(ID, code))
          .onFailure(err -> ctx.fail(401, err))
          .onSuccess(user -> ctx.json(new JsonObject().put("verified", true)));
      });

    vertx.createHttpServer()
      .requestHandler(app)
      .listen(8080)
      .onFailure(Throwable::printStackTrace)
      .onSuccess(server -> {
        System.out.println("Server listening: http://localhost:" + server.actualPort());
      });
  }
}
```

**Comment by pmlopes** [comment]
I think we can start on `totp` from here, WDYT?

**Comment by otricadziziusz** [comment]
@pmlopes Yes, I agree. I can start implementing `totp` authenticator.

**Comment by otricadziziusz** [comment]
@pmlopes I need your hint. I think i will need changes from this branch to implement the `totp`. How can I best do it?

**Comment by pmlopes** [comment]
@otricadziziusz I think the easiest is to update your fork to follow this branch instead of master.

So assuming you have a `vert-x3/vertx-auth` fork, you add a remote to this repo:

```
git remote add https://github.com/vert-x3/vertx-auth.git upstream
git remote -v
```

The list should now have 4 entries 2 as `origin` and 2 as `upstream`.

From here you cat work with git as usual:

```
git fetch upstream
git merge upstream otricadziziusz-feature/otp/hotp
```

This should try to merge this changes into your local working branch (the one you used to create the PR) so both will be in sync. Whenever you push to the PR I'll sync on my side, and only I there are some structural changes we need to resync again.

**Comment by otricadziziusz** [comment]
@pmlopes thanks, i posted the implementation totp #491

**Pull request merged**
