### PR TITLE
add gitee oauth provider

### PR DESCRIPTION
**Pull request by oschina**
Motivation:

Gitee is the largest open source code hosting platform in China, with more than 8 million registered developers, and many developers in mainland China use Gitee as a third-party login platform.

I very much hope that Vert.x can officially add OAuth authentication support for Gitee.

Conformance:

Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

### CODE REVIEW

**Comment by gaol** [comment]
Cool !

Could you please[ sign ECA](https://www.eclipse.org/legal/ECA.php) and squash your commits into one for the review ? thanks :)

**Comment by oschina** [comment]
> Cool !
> 
> Could you please[ sign ECA](https://www.eclipse.org/legal/ECA.php) and squash your commits into one for the review ? thanks :)

ECA signed and commit squashed :)

**Comment by pmlopes** [comment]
@oschina, just a quick question. Does `gitee` support openid auto discovery? If it does it would be nice to also support it as it makes configuration even easier for end users.

For example here's what, Azure does:

https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration

If you have such URL, vert.x already knows how to parse this and you can do:

```java
/**
   * Create a OAuth2Auth provider for OpenID Connect Discovery. The discovery will use the default site in the
   * configuration options and attempt to load the well known descriptor. If a site is provided (for example when
   * running on a custom instance) that site will be used to do the lookup.
   * <p>
   * If the discovered config includes a json web key url, it will be also fetched and the JWKs will be loaded
   * into the OAuth provider so tokens can be decoded.
   *
   * @param vertx   the vertx instance
   * @param config  the initial config
   * @param handler the instantiated Oauth2 provider instance handler
   */
  static void discover(final Vertx vertx, final OAuth2Options config, final Handler<AsyncResult<OAuth2Auth>> handler) {
    // don't override if already set
    final String site = config.getSite() == null ? "https://gitee.com/<base to .well-known dir>" : config.getSite(); // <--- HERE

    OpenIDConnectAuth.discover(
      vertx,
      new OAuth2Options(config)
        .setSite(site)
      handler);
  }

  /**
   * Create a OAuth2Auth provider for OpenID Connect Discovery. The discovery will use the default site in the
   * configuration options and attempt to load the well known descriptor. If a site is provided (for example when
   * running on a custom instance) that site will be used to do the lookup.
   * <p>
   * If the discovered config includes a json web key url, it will be also fetched and the JWKs will be loaded
   * into the OAuth provider so tokens can be decoded.
   *
   * @see GoogleAuth#discover(Vertx, OAuth2Options, Handler)
   * @param vertx   the vertx instance
   * @param config  the initial config
   * @return future with the instantiated Oauth2 provider instance handler
   */
  static Future<OAuth2Auth> discover(final Vertx vertx, final OAuth2Options config) {
    Promise<OAuth2Auth> promise = Promise.promise();
    discover(vertx, config, promise);
    return promise.future();
  }
```

**Comment by oschina** [comment]
> @oschina, just a quick question. Does `gitee` support openid auto discovery? If it does it would be nice to also support it as it makes configuration even easier for end users.

@pmlopes  Unfortunately, Gitee.com does not currently support OpenID, we will evaluate this and support this feature in subsequent iterations.

**Pull request merged**
